############# French navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "blog/"
weight = 2

[[main]]
name = "A propos"
url = "about/"
weight = 3
hasChildren = true

[[main]]
parent = "A propos"
name = "Contact"
url = "contact/"

# footer menu
[[footer]]
name = "A propos"
url = "about/"
weight = 1
